### ISSUE TITLE
Marc 260/264 Update

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/cihm-metadatabus#47]
Edit the MARC processing code to handle supporting both 260 and 264 fields.

**Comment by RussellMcOrmond** [comment]
The code we use tries to strip out anything that doesn't look like a date, but it isn't going to support all the variations that the field is documented to support in MARC.

https://www.loc.gov/marc/bibliographic/bd260.html
https://www.loc.gov/marc/bibliographic/bd264.html

That support would be a larger project, and would be better done as part of an enhancement of BlackLight MARC or other community project rather than custom CRKN code.
